CC=clang
SOURCES=curlkdb.c
OBJECTS=$(SOURCES:.c=.o)
SHAREDLIB=curlkdb.so
KDB_CFLAGS = -DKXVER=3
ARCH = -m32
#KDB_CFLAGS = 
#-lxml2 -lz -lm
CFLAGS= $(ARCH) -c -g -fPIC $(KDB_CFLAGS) -Wno-implicit-function-declaration -Wno-format
LDFLAGS= $(ARCH) -lcurl -lpthread -dynamiclib -undefined dynamic_lookup

all: $(SOURCES) $(SHAREDLIB)
	
$(SHAREDLIB): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -fPIC -o lib$@

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *o *.so
